language: objective-c
osx_image: xcode7.2

env:
  global:
    - WORKSPACE=Example/CircuitBreaker.xcworkspace
    - SCHEME=CircuitBreaker-Example
    - SDK=iphonesimulator
  matrix:
    - DEST="OS=8.3,name=iPhone 6"
    - DEST="OS=9.2,name=iPhone 6"

rvm:
  - 2.2.3

cache:
  - cocoapods

before_install:
  - gem install cocoapods xcpretty --no-document

script: ./script/build.sh

deploy:
  provider: script
  script: ./script/release.sh
  skip_cleanup: true
  on:
    tags: true
    condition: $DEST = "OS=9.2,name=iPhone 6"
