language: objective-c
osx_image: xcode7.2

env:
  global:
    - WORKSPACE=CircuitBreaker.xcworkspace
  matrix:
    - PLATFORM=ios VERSION=8.3 SCHEME="CircuitBreaker iOS"
    - PLATFORM=ios VERSION=9.2 SCHEME="CircuitBreaker iOS"
    - PLATFORM=osx VERSION=10.11 SCHEME="CircuitBreaker OSX"

rvm:
  - 2.2.3

cache:
  - cocoapods

before_install:
  - gem install cocoapods xcpretty --no-document

script: ./script/test.sh
