language: objective-c
osx_image: xcode7.2

rvm:
  - 2.2.3

cache:
  - bundler
  - cocoapods

xcode_scheme: CircuitBreaker-Example
xcode_sdk: iphonesimulator9.2
xcode_workspace: Example/CircuitBreaker.xcworkspace

before_install:
  - gem install bundler --no-document
