language: objective-c
osx_image: xcode7.2

rvm:
  - 2.2.3

cache:
  - bundler
  - cocoapods

before_install:
  - gem install bundler --no-document

script:
  - set -o pipefail && xcodebuild test -workspace Example/CircuitBreaker.xcworkspace -scheme CircuitBreaker-Example -sdk iphonesimulator -destination "OS=9.2,name=iPhone 6" | xcpretty
  - pod lib lint
