language: objective-c
osx_image: xcode7.2

env:
  global:
    WORKSPACE=Example/CircuitBreaker.xcworkspace
    SCHEME=CircuitBreaker-Example
    SDK=iphonesimulator
    DEST="OS=9.2,name=iPhone 6"

rvm:
  - 2.2.3

cache:
  - cocoapods

before_install:
  - gem install cocoapods xcpretty --no-document

script:
  - set -o pipefail && xcodebuild test -workspace $WORKSPACE -scheme $SCHEME -sdk $SDK -destination "$DEST" | xcpretty
  - pod lib lint
