language: objective-c
osx_image: xcode7.2

cache: cocoapods
rvm:
  - 2.2.3

before_install:
  - gem install cocoapods # Since Travis is not always on latest version
  - pod install --project-directory=Example

script:
  - pod lib lint
  - set -o pipefail && xcodebuild test -workspace Example/CircuitBreaker.xcworkspace -scheme CircuitBreaker-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
