language: objective-c
osx_image: xcode7.2

rvm:
  - 2.2.3

cache:
  - bundler
  - cocoapods

xcode_scheme: CircuitBreaker-Example
xcode_sdk: iphonesimulator
xcode_workspace: Example/CircuitBreaker.xcworkspace

before_install:
  - gem install cocoapods # Since Travis is not always on latest version
  - pod install --project-directory=Example
  - pod lib lint
